name: cinder
version: 0
summary: OpenStack Block Service (cinder)
description: OpenStack Block Service (cinder)
confinement: strict
grade: devel

apps:
  api:
    command: bin/run cinder-api
    daemon: simple
    plugs:
      - network
      - network-bind
  scheduler:
    command: bin/run cinder-scheduler
    daemon: simple
    plugs:
      - network
      - network-bind
  manage:
    command: bin/run cinder-manage
    plugs:
      - network

parts:
  cinder:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/cinder/cinder-stable-mitaka.tar.gz
    python-packages:
      - pymysql
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/mitaka/upper-constraints.txt
    build-packages:
      - libffi-dev
      - libssl-dev
      - pkg-config
      - libxml2-dev
      - libxslt1-dev
      - python-dev
  config:
    after:
      - cinder
    plugin: dump
    source: conf
