name: keystone
version: 9.2.1snapshot
summary: OpenStack Identity Service (keystone)
description: OpenStack Identity Service (keystone)
confinement: strict
grade: devel

apps:
  uwsgi:
    command: bin/apache-uwsgi
    daemon: simple
    plugs:
      - network
      - network-bind
  manage:
    command: bin/run keystone-manage
    plugs:
      - network

parts:
  keystone:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/keystone/keystone-stable-mitaka.tar.gz
    python-packages:
      - pymysql
      - uwsgi
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/mitaka/upper-constraints.txt
    build-packages:
      - libffi-dev
      - libssl-dev
      - pkg-config
    stage-packages:
      - apache2
      - libapache2-mod-proxy-uwsgi
    organize:
      etc/keystone.conf.sample: etc/keystone/keystone.conf.sample
      etc/policy.json: etc/keystone/policy.json
      etc/keystone-paste.ini: etc/keystone/keystone-paste.ini
      etc/policy.v3cloudsample.json: etc/keystone/keystone-paste.ini
  config:
    after:
      - keystone
    plugin: dump
    source: conf
