name: glance
version: 12.0.1snapshot
summary: OpenStack Image Service (glance)
description: OpenStack Image Service (glance)
confinement: strict
grade: devel

apps:
  api:
    command: bin/run glance-api
    daemon: simple
    plugs:
      - network
      - network-bind
  registry:
    command: bin/run glance-registry
    daemon: simple
    plugs:
      - network
      - network-bind
  manage:
    command: bin/run glance-manage
    plugs:
      - network

parts:
  glance:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/glance/glance-stable-mitaka.tar.gz
    python-packages:
      - pymysql
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/mitaka/upper-constraints.txt
    build-packages:
      - libffi-dev
      - libssl-dev
      - pkg-config
  config:
    after:
      - glance
    plugin: dump
    source: conf
